error.name.required=Name is required
error.name.invalid=Only alphabets allowed

error.mobile.required=Mobile number is required
error.mobile.invalid=Enter valid 10-digit mobile number

error.email.required=Email is required
error.email.invalid=Enter valid email